### ISSUE TITLE
Only works for default theme

### ISSUE THREAD

**Issue by james2432** [Wormss9/SteamDeckThemes#1]
I have the steam green keyboard and your plugin doesn't select the steam green theme correctly to modify the alpha channel

**Comment by Wormss9** [comment]
Looks like modifying other than the default theme is [not allowed](https://github.com/suchmememanyskill/CssLoader-ThemeDb/pull/121).

**Comment by Wormss9** [comment]
But no-one is stopping you from manually adding the updated theme :)

**Comment by james2432** [comment]
![PXL_20221018_162241461](https://user-images.githubusercontent.com/498547/196487624-0071dd6d-d320-4696-9594-6dd0f6c34bd9.jpg)
Weird they don't allow it, your patch works flawlessly! thanks :)

**Comment by Wormss9** [comment]
They made an [exception](https://github.com/suchmememanyskill/CssLoader-ThemeDb/pull/121)!
