### ISSUE TITLE
No longer works with preview branch line 

### ISSUE THREAD

**Issue by james2432** [Wormss9/SteamDeckThemes#2]
I tried the 1.1 and even reverted to the 1.0 version

Also using the default keyboard instead of the steam one. Transparency is no longer applied

**Comment by james2432** [comment]
did more testing and seems to only do it in game where the highlighted key doesn't update(you can hear sound, but the "selected" key doesn't update
![PXL_20221108_142024972](https://user-images.githubusercontent.com/498547/200589602-d398622d-670e-4494-9547-5704ca376225.jpg)

**Comment by Wormss9** [comment]
Are you using talking about SteamOS Beta version or Decky prerelease? Do you have issues with other keyboards as well? I don't have any issues in game mode, desktop nor in game. The theme mostly changes CSS color values, which should not the update of selected key. Does it happen only in one game? Does the default keyboard work in that game?

**Comment by james2432** [comment]
it may be a steamos issue.. I uninstalled all themes and uninstalled cssloader and rebooted, still an issue, closing
